### ISSUE TITLE
Upgrading the ECH website 

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#155]
To continue providing updates to the Ethereum community, the ECH group has decided to update the current [Ethereum Cat Herders website](https://www.ethereumcatherders.com/).  This issue will keep track of the progress of the task.
- [x] Create [requirement document with template for proposal submission](https://docs.google.com/document/d/1Dl_tuvUz7lNX7a1k3YA-fWCxZjSjc19Ty3SI3aJwlic/edit#) and [prototype](https://docs.google.com/presentation/d/1Otw9mlYLp74Aa5ght-t3uHR6RlVqJcL0cB_t5eS0e0s/edit?usp=sharing) (January 2021, week1-2)
- [x] Invite proposals with estimated effort & funds needed for the development work (January 2021, week 2-3)
- [x] Assign the development work to the best proposal/team (February 2021)
- [x] Invite the team to the ECH meeting to provide a regular update on the progress
- [x] Release of the updated website
- [x] Finish set-up at Ethereum Cat Herders GitHub repository.
- [x] Release funds for design & development.

**Comment by Souptacular** [comment]
For @alita-moore and @shanelightowler:

Please post your proposals in this GitHub issue.

My questions:

1. (Referencing Shane's document, but Alita can also provide an answer here for her's)
Does "branding" include a new logo/other assets?

2. What is the server type we are getting for $25 a month?

3. What is the format/process for posting new pages (Markdown, WYSIWYG, etc.)?

**Comment by shanelightowler** [comment]
Please see the proposal from Unvetica attached.
[Unvetica Quote for ECH Website.pdf](https://github.com/ethereum-cat-herders/PM/files/5837678/Unvetica.Quote.for.ECH.Website.pdf)

**Comment by shanelightowler** [comment]
In response to your queries @Souptacular 

1. Does "branding" include a new logo/other assets? 
This is a great question. Yes, you can expect a logo. I have attached a .PDF example of what the ECH's can expect from us. This includes a main-logo design, in addition to a 'social media' version, fonts, colors, and alternative logo designs. You will have full ownership and rights to the works' produced by us. This includes minor revisions to the branding package we propose - but no major revisions (meaning entire new direction). 


2. What is the server type we are getting for $25 a month?
Unvetica has a dedicated data center in Phoenix, AZ and two off-site locations in Washington State and Wisconsin for system redundancy and off-site backups. For the $25 a month ECH's would be given a dedicated server and staging area. Server uptime and maintenance is all done by us. 


What is the format/process for posting new pages (Markdown, WYSIWYG, etc.)?
Great question, we would actually implement a dual-system for this project. Meaning, we'd develop a fully custom WordPress-based administrative dashboard for the ECH's for non-technical users to use and maintain. This would mean that admins or other provisioned groups would have access to a WYSIWYG interface for creating pages, publishing blog posts, etc. Additionally, we'll configure this site so that it's tied into your GitHub organization. Meaning those more comfortable using CLI / GitHub can publish and manage aspects of content via PR.

**Comment by alita-moore** [comment]
nice @shanelightowler ! gotta say, I really like that idea, I think it makes more sense then hardcoding something. Not that my proposal isn't still on the table, though ;)

**Comment by michaelgiesen** [comment]
Hello All, just popping in to say hello - and potentially answer any questions regarding our proposal.

**Comment by poojaranjan** [comment]
@michaelgiesen @shanelightowler 

Thanks for sharing Unvetica proposal for the development of [Ethereum Cat Herders Website](https://www.ethereumcatherders.com/).  I've got a few questions:
- Will it be possible to update the page with a Pull Request created by someone from the community? 
- If not, what would be the process to update the page without it being dependent on an individual holding the credentials?
- How easy difficult will it be for a core member of Cat Herder to do the small changes - like adding/removing a section?
- What would be the expected (avg.) cost per year for maintenance and hosting that would be in addition to the initial proposal of development of the page?

**Comment by poojaranjan** [comment]
@alita-moore If you're still up for it, do you mind sharing your proposal here for reference?

**Comment by alita-moore** [comment]
Sure here's a link https://docs.google.com/document/d/1WqqiGRe4EweKcE-lMQ4FFQHPUH9AS1c3FpGclIhNBlo/edit?usp=drivesdk

**Comment by michaelgiesen** [comment]
@poojaranjan These are great questions. Please find the answers below, if you need additional detail please let me know and I'll be happy to expand.

> Will it be possible to update the page with a Pull Request created by someone from the community?
Yes and No. From a blog post perspective we'll be able to integrate PR's so that posts and text-based updates can be updated and published to the site. For front-end edits, that'll have to be completed via the WordPress Administrative GUI. The ECH team will be provided master administrative login credentials that will allow to add/edit/remove pages, posts, content, etc. I can also provide the ECH team SSH access to the server to directly edit core WordPress files if needed. I can provide either a single master login credentials or individual accounts, whatever is easiest.

> How easy difficult will it be for a core member of Cat Herder to do the small changes - like adding/removing a section?
This is a pretty easy task. The administrative backend is incredible intuitive and since WordPress is open source, it's incredibly well documented online as well. We (Unvetica) provide basic documentation as well on how to maintain the site. But the interface is literally a drag/drop style of managing components on pages/posts, with the ability to dive into the source code if needed.

> What would be the expected (avg.) cost per year for maintenance and hosting that would be in addition to the initial proposal of development of the page?
There is a $25 a month charge if you want us (unvetica) to host on our own servers and a $150 per month if you want us (unvetica) to maintain overall site support. This means things like WordPress updates/patching, security updates, plugin updates, backups, user management, etc.

**Comment by poojaranjan** [comment]
> There is a $25 a month charge if you want us (unvetica) to host on our own servers 

@michaelgiesen Thanks for joining us in the ECH meeting, yesterday. I hope you have some visibility of the website page that Cat Herders are looking for. Do you think the month-to-month hosting charge ($25) can be avoided and we could use free hosting by GitHub as we have it now for our present website? 
Ref: https://github.com/ethereum-cat-herders/ethereum-cat-herders.github.io

**Comment by michaelgiesen** [comment]
@poojaranjan 

No problem at all, it was great to talk to everyone about the project. To be clear the $25 charge for hosting is only if unvetica hosts the site. The ECH's are more than welcome to find alternative solutions for hosting - however since I would be developing on top of a WordPress-based platform, whatever hosting provider you solicit will need to have some sort of database capabilities. I'm not sure if GitHub provides that type of functionality. 

I would recommend some sort of platform like [WPMU Dev](https://premium.wpmudev.org/) or GoDaddy, etc.

**Comment by shanelightowler** [comment]
I have used the wordpress hosting offering in the past for wordpress sites/blogs and it was pretty easy to manage.

**Comment by shanelightowler** [comment]
Hi all, following on from the previous ECH call, there was an action to re-evaluate the proposed ECH website prototype/brief to see if there might be a need to change of tack given the decisions made re: ethereum.org website where ethereum.org is the primary source of truth, linking out to specialist resources where necessary... where does that leave the Cat Herders content? This is a decision for Cat Herders group to make, to ensure @michaelgiesen doesnt build things we wont ultimately need for the website.

On the ECH call, I think although we were all saying it differently, we were all in agreement that there is still space for the ECH website to cover the various areas ECH has interests in. These would be framed in the context of 'the ECH supports in this area, but before we just present you with a long list of links to various sources we'll tell you a bit about what this is, and what ECH does, so that you're not lost'. We would then link out appropriately to various resources that mostly exist off-site eg ethereum.org, github, youtube, medium, wherever.

And in that way we can build a content proposition that is uniquely Cat Herders, but lets the canonical sources of the content do the heavy lifting off-site. @wschwab had some good thoughts on this specifically in the call notes. Do let me know if I've got that wrong :)

To this end I've quickly reviewed both the existing website and the prototype to see where there may be content gaps/issues... 

Conclusion: I don't think there's anything significant that needs to be stripped out as a lot of the content on the ECH website already exists as an index of links... rather, the area to focus on would be on ensuring that for each key section (eg around EIPs, upgrades, dev meetings) we present the Cat Herders context up front, and then lead into the resource links straight after.

So as per @Souptacular 's suggestion, I've created the following [google doc](https://docs.google.com/document/d/1kbU5FwPQLAT7TAuSKzVhuAwDcW_lBKpP0cyqVm7JbiQ/edit#) which lists out the content both on the current website and then the new website. The new website is based off of the existing prototype but also some slight refinements from me based on the conversations happening in the calls/discord. This obviously all up for feedback - I'm not assuming my suggestions are sacrosanct.

If we are ok with this as a structure, I believe this would then give @michaelgiesen sufficient steer to carry on with the work.

There would also be some decisions for Cat Herders to make around workflow (ie how specifically does content get approved/uploaded) and also the fine detail of content in each section, but those are in the future for now.

**Comment by michaelgiesen** [comment]
Hello All,

We're developing the site so that there will be a version of the website live for the next ECH meeting (03/30/21). Specifically the Home/Landing page that will have full functionality, and then a "streaming" page which will allow ECH meetings to broadcast (stream) their meetings to. 

With that being said, I want to start preparing the logistics for this. Mainly, where is the TLD hosted? I'm curious how we handle the nameserver transition so that we're prepared before Tuesday.

**Comment by BrentAllsop** [comment]
Charles St.Louis (CPSTL)
@CPSTL  is the owner of the ethererumcatherders.com domain.
We just need to get him a new IP address, and he can update it.
I can do that, if you get me the IP.

**Comment by michaelgiesen** [comment]
@BrentAllsop and/or @CPSTL in regards to pointing the domain to the new hosting, is it simply _just_ the IP address you need, or do you need the new nameservers?

**Comment by BrentAllsop** [comment]
Just the IP address.

**Comment by michaelgiesen** [comment]
@BrentAllsop 173.201.185.67

**Comment by BrentAllsop** [comment]
> @BrentAllsop 173.201.185.67

Whenever the new sight is ready at this location, we can just give this IP to @CPSTL and he can make the switch.

**Comment by michaelgiesen** [comment]
All,

Here is the live staging site where everyone can see the progress being made. We're still working on applying the content in some places, but if you'd like to see everything laid out please view here:

http://ethereumcatherders.site/

please let me know of changes if you see something glaring so we can get those updated ASAP.

**Comment by alita-moore** [comment]
@michaelgiesen 😮 that looks... amazing. I would say a little better than the original, lol.

**Comment by michaelgiesen** [comment]
@alita-moore thank you thank yoU! :)

**Comment by shanelightowler** [comment]
I agree, looking fantastic!

**Comment by michaelgiesen** [comment]
Ethereum Cat Herders site is now ready to launch. @BrentAllsop can we get this switched over so it's published to the live domain? 

current IP address: 173.201.185.67

**Comment by poojaranjan** [comment]
Hi @michaelgiesen 
We missed you in the ECH meeting today. Would you please leave an update on the progress? Either here or on the [agenda](https://github.com/ethereum-cat-herders/PM/issues/206) is fine.  
Thanks!

**Comment by michaelgiesen** [comment]
@poojaranjan I would consider this project officially 'done'. As of 06/22/21 1:30PM PST the EthereumCatHerders.com is now being hosted on unvetica infrastructure and fully integrated with GitHub. The Website repo can be found here: https://github.com/ethereum-cat-herders/ech-website-v2

For website updates all you'll have to do is submit a PR, once changes have been merged in they'll be deployed to the live site.

**Comment by BrentAllsop** [comment]
I get 404, page not found with that link.

**Comment by poojaranjan** [comment]
I just changed the visibility. @BrentAllsop can you please try again? Let me know if you still find the error.

**Comment by BrentAllsop** [comment]
@poojaranjan 
> I just changed the visibility. @BrentAllsop can you please try again? Let me know if you still find the error.
Oh, there it is, now I see it, thanks.

**Comment by poojaranjan** [comment]
@michaelgiesen thanks for integrating the content with the ECH GitHub. 

On review of the live website, it seems like there are issues with sync and some of the requested updates as listed [here](https://docs.google.com/document/d/1kbU5FwPQLAT7TAuSKzVhuAwDcW_lBKpP0cyqVm7JbiQ/edit#) & [here](https://docs.google.com/document/d/1DA69jNqli7a4g_hEih52xpA5SrhvR-CC81lXnG9lhxQ/edit#) are still outstanding.

Apart from this, we would need info on 
- User id & Pwd of the website to manage content (if needed). We'd also like to understand the process for future _Website Maintenance & Support_. eg.  what would be SLA for submission,  tracking & expected days of completion of requests.
- Where and how to collect analytics. User id & Pwd to be shared with ECH members.

As mentioned in one of the ECH calls, a meeting explaining how the website updating process would work will be appreciated. Please propose date(s) in the ECH Website channel to get this meeting organized sooner rather than later. Please feel free to reach me with any questions. Thanks!

**Comment by michaelgiesen** [comment]
@poojaranjan It's unclear to me what you're specifically referencing with the two links. What I suggest is a meeting to discuss the workflow and to be able to show this via screenshare. 

I find the share google docs to be a big confusing to follow over time, I think being able to apply the development workflow and maintain everything via GitHub will be more efficient. Once I have this workflow demoed ECH's can follow that in order to maintain update on the site. 

I have sporadic availability throughout the week. Do any of these windows work to have a DEMO:

- Tuesday, June 29th @ 2:00PM UTC
- Wednesday, June 30th @ 5:00PM UTC
- Thursday, July 1st @ 2:00PM UTC
- Friday, July 2nd @ 4:00PM UTC

Please let me know what works best and I'll create a zoom meeting link.

**Comment by poojaranjan** [comment]
> It's unclear to me what you're specifically referencing

Listing a few for your reference.
- The home page TV section is still outdated.
- Latest video button does not show the latest video
- PEEPanEIP tab shows EIPIP meetings
- There is no playlist for EIPIP meetings 
- Which one will be used when a meeting is Live streamed? 
- Edson Ayllon is not listed as members
- EIP resources shared on June 7 [here](https://docs.google.com/document/d/1DA69jNqli7a4g_hEih52xpA5SrhvR-CC81lXnG9lhxQ/edit#) is not reflected. 
There are more edits that were requested to be added a while ago. A review would be nice to complete the updates. 


> I find the share google docs to be a big confusing to follow over time

Agreed. We can make use of GitHub. I will look into creating a project for the ECH website with Kanban basic (To do - WIP - Completed) to keep track of requests submitted and closed. Open to suggestions. 

> For the meeting
I am available on (a) Tuesday, June 29th @ 2:00PM UTC and (b) Friday, July 2nd @ 4:00PM UTC. Would prefer (a) if it works with others too. @shanelightowler, @BrentAllsop, @Santhosh1692 have shown interest to join the meeting. Does (a) work for you? Just FYI, we will also record the meeting for future reference.

**Comment by Santhosh1692** [comment]
@poojaranjan : I am available for option (a).

**Comment by poojaranjan** [comment]
@michaelgiesen  @shanelightowler, @BrentAllsop, @Santhosh1692 

Let'sconnect in a couple of hours (on Tuesday, June 29th @ 2:00 PM UTC). I have DM'd the zoom link to everyone on Discord.

**Comment by poojaranjan** [comment]
As it turns out this was short notice.  happy to reschedule the meeting to **Friday, July 2nd @ 4:00PM UTC** @michaelgiesen.

The same zoom link can be used for the meeting.

**Comment by BrentAllsop** [comment]
Sorry If I missed a meeting, I am interested in this.

**Comment by poojaranjan** [comment]
> Sorry If I missed a meeting, I am interested in this.

@BrentAllsop you didn't miss it. We will meet on **Friday, July 2nd @ 4:00PM UTC**

**Comment by BrentAllsop** [comment]
That's 10:00 am, my time.  Just added it to my calendar.

**Comment by poojaranjan** [comment]
@michaelgiesen something came up and I may not be able to make it on Friday. Can we move it to Tuesday, **July 06 @ 4:00 PM UTC** (just after the ECH meeting)?

cc: @BrentAllsop @Santhosh1692 @shanelightowler

**Comment by BrentAllsop** [comment]
I have something at 4:00 pm UTC on Jul 6, but could move it.

**Comment by michaelgiesen** [comment]
@poojaranjan That's not a problem. I will be available and attend the ECH meeting on Tuesday, July 06 @ 4:00 PM UTC

**Comment by poojaranjan** [comment]
@michaelgiesen 

Cool! It will be nice to have an update on the syncing issue, missing details on the website & an estimated turnaround time on any requested service. Talk to you soon! 

(We can use the ECH meeting zoom link to join & record the webiste-development meeting. I will share it afterwards for people to follow, if anyone can not make it to the meeting today.)

**Comment by poojaranjan** [comment]
ECH website is now hosted via GitHub.
