### ISSUE TITLE
Ethereum Cat Herders Engineering (July 2021)

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#211]
ECH engineering tasks (July 2021)

Contd. from [June 2021](https://github.com/ethereum-cat-herders/PM/issues/208)
- [ ] https://github.com/alita-moore/PM/issues/5
- [ ] https://github.com/alita-moore/PM/issues/4
- [x] https://github.com/alita-moore/PM/issues/3

New addition
- [x] https://github.com/alita-moore/PM/issues/6
- [x] https://github.com/alita-moore/PM/issues/7
- [ ] https://github.com/ethereum-cat-herders/EIPIP/issues/73#issuecomment-879999394 (bot that marks EIPs as stale daily)
- [x] https://github.com/alita-moore/PM/issues/8
- [ ] https://github.com/ethereum/EIP-Bot/issues/5
- [ ] https://github.com/ethereum/EIP-Bot/issues/6
- [ ] https://github.com/ethereum/EIP-Bot/issues/7
- [ ] https://github.com/ethereum/EIP-Bot/issues/8

**Comment by alita-moore** [comment]
@poojaranjan it makes the most sense to me to put all engineering related tasks on my plate my adding them here. I may be too busy with other things to get to them quickly, so you can try and find people to do them. If those people don't / no one jumps on then I will _eventually_ get to it :) I have added on the website banner + marking EIPs as stale bot. I am just going to tackle things kind of in random orders, but if you want to have an agile style sprint kickoff / priority planning sessions biweekly / at the ECH meeting that would also be fine. This will also be helpful because it will let us easily hire on other people as they become available / necessary but I will nevertheless be working on it at all times.

**Comment by poojaranjan** [comment]
@alita-moore 
We can remove the issue "_Add a warning label to all non-finalized EIPs_" from the list as a pull request has been submitted to complete the task. The pull request looks good to me. As soon as it is merged, will close the issue. 

I would appreciate tasks being managed in an orderly fashion. You may leave the tasks open for the community if you have bandwidth issues but feel free to move/add it to your list if there is no response till the time you're available to work on it and finish up in the respective month. 

I would hate to overwhelm you with tasks over your contract time, so an estimate on efforts will be helpful to put out a bounty on tasks to be completed sooner rather than later if there is an overflow of engineering tasks.

**Comment by alita-moore** [comment]
Sure, that makes sense. I think that it would make sense to treat this as a list of tasks to be completed and then every ECH we can prioritize / promise some of the tickets. 

For instance, I promise to that I will fix the bugs with the EIP Bot, write the stale EIP bot, and finish writing the bot tests by next ECH. 

Does this sound good to you? This will also give me the ability to say that X amount of work is too much for those two weeks and I / we can write up a bounty so work can start.

**Comment by poojaranjan** [comment]
Sounds good!

**Comment by alita-moore** [comment]
per the ECH meeting I will be working on (in order of priority)
- [ ] https://github.com/alita-moore/PM/issues/6
- [ ] https://github.com/alita-moore/PM/issues/7
- [ ] https://github.com/ethereum-cat-herders/EIPIP/issues/73#issuecomment-879999394
- [ ] https://github.com/alita-moore/PM/issues/3

By the next ECH meeting on August 3rd (although I will have these done before august 1st)
