### ISSUE TITLE
Where should the Eth1.x online discussion take place?

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#51]
What is the home for Eth1.x specific discussions?
Is it ethresear.ch, ethmagicians, or would it be best to have it's own focused environment?

This is from my own observation that many of the replies to Eth1.x related discussions on ethresear.ch is some form of "this isn't an issue when we move to PoS". How many Eth2 eyes need to see eth1.x and visa versa? 

Perhaps mixing the discussions makes finding the relevant discussions more difficult. 
Perhaps it is better to have both in the same place as to keep both updated on progress.

**Comment by poojaranjan** [comment]
Perhaps the best (most authentic)  way  to share communication regarding Ethereum is [Ethereum Blog](https://blog.ethereum.org).

Fastest way of communication is [Ethereum Twitter](https://twitter.com/ethereum) and then follows [ECH Medium](https://medium.com/ethereum-cat-herders/stories/published) because essentially it is for Ethereum support.

[Fellowship of Ethereum Magician](https://ethereum-magicians.org) - For discussion, as it is the centre of discussion for major changes / process improvements of Ethereum blockchain for contributors (developers). Also, it is the vital place stores the conversation that may be accessed or referred later.

[ACD Gitter](https://gitter.im/ethereum/AllCoreDevs) - Good for discussion with limited users but will not be good to refer in future.

[Ethereum Reddit](https://www.reddit.com/r/ethereum/) - For users and community to know as we have wide users available there than the Gitter channel

**Comment by bmann** [comment]
@MadeofTin I think the default is here --> https://ethereum-magicians.org/c/working-groups/ethereum-1-x-ring

And then each Working Group can either use the forum and create their own ring, or use a communication forum of their choice.

I'm assigning this to you if you want to pursue it further?

**Comment by lrettig** [comment]
Seconded, FEM forum eth1x ring is probably the right place. I can imagine there might be *some* more research-y type things that could land on ethresear.ch.
