### ISSUE TITLE
Introducing New Transaction Format 

### ISSUE THREAD

**Issue by MadeofTin** [ethereum-cat-herders/PM#54]
Possibly extending from Vitaliks proposal.

**Comment by lrettig** [comment]
Cf. https://ethereum-magicians.org/t/fee-market-change-working-group-formation-and-my-proposed-amendment/3195. This is also possibly relevant for state rent since we may want to add a TTL field to the transaction to prevent replay attacks (although I believe this is not required in the most recent version of @AlexeyAkhunov's proposal).

**Comment by timbeiko** [comment]
@MadeofTin @lrettig now that this working group has been kicked off, does it make sense to close this issue?

**Comment by lrettig** [comment]
I believe this is being covered by the fee market change working group which @afdudley is on top off. Nothing pending here that I'm aware of.
