### ISSUE TITLE
Hard Fork Planning and Coordination Meeting #2 - Agenda

### ISSUE THREAD

**Issue by poojaranjan** [ethereum-cat-herders/PM#60]
## Date and Time

Proposed time is 14:00 UTC on Wednesday, April 24th, 2019.
Meeting duration: 1 hr

## Location 

Zoom: The link will be shared soon.

## Agenda 

1. Berlin meetup update.
2. Discuss [ECH issues](https://github.com/ethereum-cat-herders/PM/issues) (Istanbul / upgrade process specific), volunteer for tracking and closing?
3. Status on [EIP proposed](https://github.com/ethereum-cat-herders/PM/blob/master/Hard%20Fork%20Planning%20and%20Coordination/IstanbulHFEIPs.md).
4. EIP approval process. Who are the decision makers?
5. Improvements to Hardfork Meta process [#1852](https://github.com/ethereum/EIPs/pull/1852).
6. [EIP 1929](https://github.com/ethereum/EIPs/blob/16e64a488cd16403b884417799074aae77be41ab/EIPsForHardfork.md)(ECH proposal for HF coordination).

**Comment by poojaranjan** [comment]
Previous meeting [notes](https://hackmd.io/SyvehR7kSdWpCS2GV4Y3oQ?both) for reference.

**Comment by bmann** [comment]
Unfortunately I can’t make it tomorrow. Thanks for putting this together. Here are my comments:

1) Lots, still working on it. See new wiki page https://en.ethereum.wiki/eth1 and then summary of all talks here https://en.ethereum.wiki/eth1/coredevsberlin

Maybe another one in late July?

Danno has volunteered to move forward on Hardfork timing. Right now, likely to be 6 months for the next one, so April 2020. 

There is a lot to do and a lot of issues. Grooming these and seeing who can answer them or how they need to be organized would be helpful. 

2) I entered in a lot of issues from the CoreDevsBerlin, plus I’ve been adding Ethereum Foundation “bugs” 

I entered in milestones that map to current HF dates https://github.com/ethereum-cat-herders/PM/milestones

I also added a number of labels that map to Working Groups. 

For issues, if it’s not assigned to anyone — it’s up for grabs! ie it is not going to get done. 

I also created a top level Istanbul project https://github.com/orgs/ethereum-cat-herders/projects/2

I put it at the top level so that it can be managed across more repos. 

I hope we can expand on this and see how this can be useful on reviewing progress on a weekly basis. 

Also feel free to push back if this is too much ;) I thought that ECH PM repo can be a good home base. Getting access to do this in Ethereum organization hosted repos will likely be much tougher. 

3) Changes to EIP233 just got merged. Next task is to communicate that PRs need to get made to 1679. 

Also — let’s not track in multiple places. The Ethereum wiki works well for overview tracking I think https://en.ethereum.wiki/roadmap/istanbul 

And, once EIPs are formally PR’d to 1679, this page will update automatically http://eips.ethereum.org/EIPS/eip-1679

4) once proposed, Core Devs need to accept. Then has to be implemented, pass testing, and be ready when the hardfork comes around. 

I was kind of thinking that late July meeting could be go / no go for some EIPs. 

5) Merged! Now on to using the template to have EIPs be PR’d into 1679

6) I still don’t understand this, sorry. It also seems to embed ECH into the process. From 5, the process is to PR against the Hardfork Meta. 

Once we know which EIPs are proposed, here is a basic tracker https://en.ethereum.wiki/roadmap/istanbul/tracker

**Comment by poojaranjan** [comment]
Thanks @bmann for updates. It looks good. We will revisit later.

**Comment by poojaranjan** [comment]
[EIP 1929](https://github.com/ethereum/EIPs/blob/16e64a488cd16403b884417799074aae77be41ab/EIPsForHardfork.md) is basically the extension to [EIP 233](https://eips.ethereum.org/EIPS/eip-233).

As per the last merge, EIP 233  gives the high level overview of EIP inclusion process for the HF. It says that, "_Anyone that wishes to propose a Core EIP for the hard fork should make a PR against the Meta EIP representing the hard fork_." 

But, that doesn't explain the process flow of EIP, from EIP proposal to the upgrade readiness. That is actually documented in EIP 1929. 

Of course, a mention about EIP 1929 in EIP 233 (in "EIP Inclusion Process") would help forthcoming HF coordinators in managing it effortlessly.  

**Why we need a separate EIP for the "Formal process of selection of EIPs for hardforks (Meta EIP#)" instead of EIP 233?**

Because 

1. EIP 233 describes "Formal process of hard forks". It **specifies how to create a Meta EIP** for the upcoming upgrade. 

My understanding is, this document is required by the user/group who are involved in the coordination of the HF and not by every EIP author/champion who wants to submit EIP for consideration needs to follow this.

Whereas, EIP 1929 is a document that **explains process of selection of EIPs for hardforks** (for that Meta EIP#) and it could be widely used by EIP champions once they are ready to propose it for upcoming HF.

2. In case of future edit (addition and deletion) in process flow, we don't need to disturb the master document which is EIP 233 in this case. Basically the same reason we do not want to edit the EIP 1 and introduce other EIPs to improve the system.

Hope this helps you. 



"It also seems to embed ECH into the process."

**Yes**. ECH is created to support Ethereum with project management work, which essentially means tracking and coordination. So, in order to streamline the process,  make it easier for devs to follow and track the process by a PM team member; we propose to embed ECH into the process. So that the process should be independent of person and anyone can perform the task with the document / process in place.

**Comment by poojaranjan** [comment]
Discussed in [ACD#60](https://github.com/ethereum/pm/issues/95)
